### ISSUE TITLE
Locales pour login

### ISSUE THREAD

**Issue by Moobster** [INTMSNCF/tickets-dashboard#16]
Pour faciliter la traduction d'une langue à une autre

**Comment by alograg** [comment]
Change dialog_* pour un propiete, exemple: footer.copy

https://github.com/INTMSNCF/tickets-dashboard/blob/d00f7cf8f33634d756daf80a03935744a23e1374/src/locale/fr.js#L17-L21

https://github.com/INTMSNCF/tickets-dashboard/blob/d00f7cf8f33634d756daf80a03935744a23e1374/src/locale/fr.js#L25-L28
