### ISSUE TITLE
Graphe Vertical: Repartition Mensuelle

### ISSUE THREAD

**Issue by Moobster** [INTMSNCF/tickets-dashboard#61]

**Comment by Moobster** [comment]
![repartition annuelle](https://user-images.githubusercontent.com/45401704/106757171-55dde180-6630-11eb-93ba-b3fa6d5e3bda.PNG)

**Comment by Moobster** [comment]
Comme la repartition annuelle mais mensuelle

**Comment by alograg** [comment]
Duplicate of #60
